# -*- coding: utf-8 -*-
"""Interactive Dashboard for Finance.streamlit_app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1knSd_Qsd37QGLTSS2Lz3cJod_DEdTLNB
"""

!pip install streamlit

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st

!pip install rfc3987

from IPython import get_ipython
from IPython import display
import pandas as pd
import numpy as np
from datetime import datetime, timedelta
import plotly.graph_objects as go
import plotly.express as px

# Sample data.
dates = pd.date_range(datetime.today().date() - timedelta(days=6), periods=7, freq="D")
bills = [120, 75, 300, 40, 600, 90, 50]   # bill amounts
sugar = [110, 115, 120, 130, 125, 160, 112]  # blood sugar mg/dL
weight = [70, 70.2, 70.1, 70.3, 70.4, 70.2, 70.1]

df = pd.DataFrame({
    "Date": dates,
    "Bills": bills,
    "BloodSugar": sugar,
    "Weight": weight
})

# Alerts logic.
alerts = []
for i, row in df.iterrows():
    if row["Bills"] > 500:
        alerts.append(f" High bill on {row['Date'].date()}: ${row['Bills']}")
    if row["BloodSugar"] > 150:
        alerts.append(f" High blood sugar on {row['Date'].date()}: {row['BloodSugar']} mg/dL")

print("=== Alerts ===")
for a in alerts:
    print(a)

# Bills bar chart
fig_bills = px.bar(df, x="Date", y="Bills", title="Bills Overview", color="Bills")
fig_bills.show()

# Health trends line chart
fig_health = go.Figure()
fig_health.add_trace(go.Scatter(x=df["Date"], y=df["BloodSugar"], mode="lines+markers", name="Blood Sugar"))
fig_health.add_trace(go.Scatter(x=df["Date"], y=df["Weight"], mode="lines+markers", name="Weight"))
fig_health.update_layout(title="🩺 Health Status Trends", xaxis_title="Date", yaxis_title="Value")
fig_health.show()